### ISSUE TITLE
[mini_viewer] Crash when switching between documents in data browser

### ISSUE THREAD

**Issue by LStruber** [populse/populse_mia#233] opened 2021-10-27 13:07 UTC
Minimum steps to reproduce:
- Open a project with several files
- Edit tags of subjects (for example setting the age or name of each subject)

This process of editing is very long, and sometimes MIA crashes with 'exit code 137'
`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`

tested on linux (Ubuntu 21.04) with a MIA installation in a virtual environment and on a windows subsystem for linux (WSL2 - Windows 10 - Ubuntu 20.04) with a MIA installation with brainvisa singularity image

**Comment by servoz** [comment] 2021-11-04 11:45
Recent tests with (@LStruber, @servoz and @urlub) seem to indicate that this issue is not really related to tag editing.
It could be that the issue comes again from the memory accumulation each time an image is loaded in the miniviewer, as we had already observed it in the past (#177). This issue seemed to have been fixed earlier (7ced390).
It could be that the problem raised here is related to the data you used, indeed I do not observe it with [the data provided in populse_mia](https://github.com/populse/populse_mia/tree/master/data_tests/Philips_files/Data_patient).
@LStruber, please, can you provide the data to solve this ticket?
If I'm not wrong, this minimal teps to reproduce is simply switching from one document to another in the Data Browser (no need to change the tags). Can you confirm this, @LStruber ? If so, please change the title of this ticket to make it more explicit.

**Comment by LStruber** [comment] 2021-11-05 08:21
Yes I confirm that switching between documents is enough to reproduce the crash. Data used to produce this bug are big so I dropped them here : https://filesender.renater.fr/?s=download&token=21fe356c-288b-497d-badf-7f6c2ac7a911 (expiration date: 20/11/2021)

**Comment by servoz** [comment] 2021-11-05 08:37
Thanks @LStruber! So, we will try to fix this issue before 20/11/2021!

**Comment by servoz** [comment] 2021-12-08 12:58
Please, @LStruber, can you send again the data? (the deadline on filesender is exceeded)

**Comment by LStruber** [comment] 2021-12-09 08:15
https://filesender.renater.fr/?s=download&token=e4aa015d-0176-41fe-b4c7-27a23d84f268

**Comment by servoz** [comment] 2021-12-09 09:19
Ok it is only nii file. There is no json file?
It's just to  be sure that there is no problem with the raw data?

What is clear is that if there is no json, there will be no metadata in the database (databrowser). I don't think this is the cause of the issue in this ticket... although it's been several months since I last looked at the module, I'll have to bury myself into it first before to be sure.

**Comment by LStruber** [comment] 2021-12-09 15:47
These are the nifti data directly extracted from the scanner. If you prefer here is a link of same data (even if file names are differents due to BIDS requirements) with the corresponding *.json:

https://filesender.renater.fr/?s=download&token=81449d48-dd69-4b71-96cd-dd910fc0944a

But anyway, I'm sure there is no problem with the raw data, I visualized it, process it etc. on my side.

**Comment by servoz** [comment] 2021-12-09 16:49
I reproduce the issue with your data ... this is good news !

**Comment by servoz** [comment] 2021-12-13 15:35
There was a problem in the mini_viewer operation. The list of known images in the mini_viewer kept growing, whereas it is only necessary to keep the last selected images. This issue has now been fixed.

However, for some reason we don't yet know, the @LStruber's data produce an increase in memory due to nibabel's [as_closest_canonical()](https://nipy.org/nibabel/reference/nibabel.funcs.html#nibabel.funcs.as_closest_canonical) method. Before the fix allowing not to increase indefinitely the number of images, there was at each selection an increase of the memory, then of the swap... then a crash of the mia.

The fix is a real improvement, but to really and cleanly solve the problem of this ticket, we should know why the `as_closest_canonical()` command produces this increase in memory usage for the @LStruber' data ... It is not very easy because the `as_closest_canonical()` method is like a black box (unless we go to read the codes in nibabel), so it is difficult to know at the moment what produces this increase in memory use for the @LStruber' data.

As a reminder, we have already faced a memory issue #177 that we have solved in the past by using np.asarray(img.dataobj) which returns the array, but does not keep a reference to the array in memory (nibabel get_fdata() will load the image array into memory, return it, and also keep a reference to the array of the image). With this patch we had not observed any more memory issue until the recent use of the @LStruber's data!

In my opinion we have (at least) two ways from now:

  - if the fix makes it possible not to have any more crashes and an acceptable operation (not too slow, etc.), perhaps we could close this ticket in order not to invest too much time in the mini_viewer which is not essential since we have now an operational data_viewer ((the crash risk in this case will always exist in the case of a user with a low memory computer if he wants to display at the same time several images like the one of @LStruber , in the mini_viewer...)
  - We decide to find another way instead of `as_closest_canonical()`  to place the images in the RAS coordinate system so that we can compare the images in the miniviewer.

@LStruber's, can you test with your data the master branch ? and tell us if you now observe a crash of mia and if the use of your data in the data browser is OK (I don't observe slowness with my computer but it is a racehorse!!!). The result will help us to make a decision!

**Comment by LStruber** [comment] 2021-12-14 16:59
Just tested it on master branch with the data I provided. It does not crash anymore and my RAM usage does not grow "indefinitely" as before ! Moreover switching between documents and editing tag names is faster than before.

In my opinion, this ticket can be closed.

**Closed** 2021-12-14 22:51 UTC
Labels: To discuss
