### ISSUE TITLE
appveyor is in error since e48cd2e24

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#134] opened 2019-12-05 12:37 UTC

**Comment by servoz** [comment] 2019-12-12 21:49
This ticket was closed following f42ead1 ?
Is there not a better way to close this ticket for fixing the problem than to delete it?

**Comment by M40V** [comment] 2019-12-19 13:07
Currently I'm unable to reproduce the appveyor fail on my station, the failure of this test is specific to appveyor, it works on travis and my station. I propose to make a note of the problematic test in the #87 issue that handle code coverage and close this issue.

**Comment by servoz** [comment] 2019-12-19 13:17
The tests are no longer in error with appveyer since you have deleted the test test test_save_project (f42ead1). This is not a  fix, it's just a deletion, right? (the subject of my previous question) ... I guess it would be cool to close only when the problem is fixed.

**Closed** 2020-01-29 13:35 UTC
Labels: bug
