### ISSUE TITLE
Populse-mia 1.3.0 has requirement scikit-image==0.15.0 (ValueError: Big-endian buffer not supported on little-endian compiler)

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#153] opened 2020-03-24 13:52 UTC
**Describe the bug**

After importing data (philips dataset from the data in populse_mia sources), I have 2 images in the data browser. When I click on any of them, mia crashes with the error below.
It did not happen before (or maybe I forgot which dataset I was using) so I suspect the change might be in skimage: yesterday I have pip udpated some packages, and it did update many packages outside of my control (did I tell you I don't like pip ?)...
I have skimage version 0.16.2 on an Ubutnu 18.04.

**Generated error**
```
Traceback (most recent call last):
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/data_browser.py", line 2085, in selection_changed
    self.data_browser.connect_mini_viewer()
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/data_browser.py", line 333, in connect_mini_viewer
    self.viewer.verify_slices(full_names)
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 776, in verify_slices
    self.show_slices(file_paths)
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 580, in show_slices
    self.image2DModifications(idx)
  File "/mnt/sys2/home/riviere/neurosvn/populse/populse_mia/master/python/populse_mia/user_interface/data_browser/mini_viewer.py", line 415, in image2DModifications
    anti_aliasing=False)
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py", line 856, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 70, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler
```

**To Reproduce**
1. open populse_mia
2. import data
3. in the import tool, select "Philips", then select the philips dataset
4. add the selected data to the basket and export it to MIA. 2 images appear in MIA's data browser.
5. (You can save the project here to start from here next time)
6. click on any of these 2 data
7. boom.

**Expected behavior**
No crash. No error. The dataset should be displayed at the bottom of MIA window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Populse_MIA version 1.3.0 (master)

**Additional context**
skimage version 0.16.2
numpy version 1.18.2

**Comment by servoz** [comment] 2020-03-24 14:17
work around ...
in my station:

```
$ pip3 show skimage
WARNING: Package(s) not found: skimage
$ pip3 show scikit-image
Name: scikit-image
Version: 0.15.0
etc.
$ python3
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage
>>> skimage.__version__
'0.15.0'
```
So is the problem related to a version higher than 15.0?
I will upgrade scikit-image to the last one (0.16.2) and see if I see the same problem!problem for a version higher than 15.0?
I will upgrade scikit-image to the last one (0.16.2) and see if I see the same problem!

**Comment by servoz** [comment] 2020-03-24 14:27
```
$  pip3 install scikit-image --upgrade
Collecting scikit-image
  Downloading scikit_image-0.16.2-cp37-cp37m-manylinux1_x86_64.whl (26.5 MB)
     |████████████████████████████████| 26.5 MB 207 kB/s
etc.
ERROR: populse-mia 1.3.0 has requirement scikit-image==0.15.0, but you'll have scikit-image 0.16.2 which is incompatible.
etc.
```
I will try now to see if i reproduce but it seems  a good idea to stay with scikit-image==0.15.0 ...

**Comment by servoz** [comment] 2020-03-24 14:46
Ok i reproduce with scikit-image == 0.16.2.
In one hand we can suggest to stay for now with scikit-image == 0.15.0 or one other hand we can try right now to change code to run with latest version of scikit-image ...
I have no idea if it's a big job, if it's a bug in the last version of scikit-image (in this case we can hope that it will be solved in a future version), etc ...
If it's not a bug, we have to fix it in order to don't stay stuck to this 0.15 version ...
For now we stay with 0.15, and we wait and see ?

**Comment by denisri** [comment] 2020-03-24 14:58
OK.

**Comment by denisri** [comment] 2020-03-24 15:01
I confirm that using skimage 0.15.0 the problem disapears.

**Comment by servoz** [comment] 2020-03-24 16:19
Just to remember:
[If we don't get feedback from the scikit-image team](https://github.com/scikit-image/scikit-image/issues/4525)...  I ran some tests a couple of months ago (I don't remember exactly the details !!!) which showed that nibabel was a very interesting alternative to skimage (as I don't remember the details but I remember it was better with nibabel !). Something like that:

```
import nibabel.processing as nibp
mask_final = nibp.resample_from_to(mask, ref3D, order=self.interp)
```

in place of

```
from skimage.transform import resize
resized_mask_data = resize(mask_data, ref_size, order=self.interp, mode='reflect')
```

**Comment by servoz** [comment] 2020-03-25 16:04
So, according to the [small investigation](https://github.com/scikit-image/scikit-image/issues/4525), it seems that changing
 ```
im2D = resize(im2D, display_size, mode='constant',
                          anti_aliasing=False)
```
to
```
im2D = resize(im2D.byteswap().newbyteorder(), display_size, mode='constant',
                          anti_aliasing=False)
```
in populse_mia.user_interface.data_browser.mini_viewer.MiniViewer.image2DModifications(), is a possible fix

This is my 2 cents hack to fix this issue (tested today with skimage==0.15.0 and skimage==0.16.2). 
I propose to wait and see a little bit in case the scikit-image team make a change in this way directly in the scikit-image library
When we will close this ticket we must not forget to remove the scikit-image==0.15.0 requirement in info.py

**Comment by denisri** [comment] 2020-03-26 09:19
in `im2D.byteswap().newbyteorder()` if I understand, we assume that the image has a different byte order from the machine, but I guess we cannot make this assumption for every image ? We would need to check the image byte order first, no ?

**Comment by servoz** [comment] 2020-03-26 09:32
Yes, I agree! I don't really know actually, like I said it's just a 2 cents hack ... But I guess if the image already has the same byte order, using im2D.byteswap().newbyteorder() won't change anything? I think this work should be done directly in the skimage library ...

**Comment by servoz** [comment] 2020-03-31 04:55
I reopen this ticket since CI are now failing because scikit-image 0.16+ supports only Python 3.6 and above ...
So we have two options:
-1 We remove python 3.5 from populse_mia requirements (and we add 3.8) ?
-2 As I previously write, we change skimage.transform.resize() by nibabel.processing.resample_from_to() (nibabel needs Python 3.5.1 or greater) ?

**Comment by denisri** [comment] 2020-03-31 09:48
* Python 3.5 is the version in Ubuntu 16.04 which is still widely used ans will be supported one more year (and it is the version still in use in our lab), so I'm not comfortable with dropping support for 3.5 yet.
* is nibabel a strong dependency of populse_mia ? I'm not completely comfortable either with completely relying on nibabel because we also have lots of neuroimaging libraries here and nibabel took completely different conventions from ours, and it's very difficult to mix both without making mistakes, and I would like to be able to make plugins using out libraries, too. Now if the small viewer is a plugin that can be unplugged, in a specified area of the code, it could be OK.
* What's the problem with sticking with skimage 0.15 when using python 3.5 ?

**Comment by servoz** [comment] 2020-03-31 10:14
Okay, I completely understand the arguments for the first two points.

For the last point, well ... to my knowledge there is no problem with using skimage 0.15 when using python 3.5 !!! 
In fact, it was mostly because before we were stuck with skimage 0.15 due to populse_mia crashes with higher version and ...  without having taken the time to try to understand why.
After the last investigations we now know why and how to fix and it seemed interesting to stop blocking skimage at the version 0.15 in order to follow the evolutions.
Now we can continue to stay stuck at version 0.15 for another reason (still needing python3.5 is a very good reason, and better that before !).
Well, I roll back to scikit-image==0.15.0 in the  REQUIRES list ? :-)

**Closed** 2020-03-31 10:31 UTC
Labels: enhancement
