### ISSUE TITLE
[iteration] Issue when using ReduceNode brick 

### ISSUE THREAD

**Issue by manuegrx** [populse/populse_mia#309] opened 2023-07-07 10:24 UTC
**Describe the bug**
As explain in the populse_mia [procedure](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#pipeline-iteration), if the parameter to be iterated on is a list, we need to use a node which transform a single file (input for this iteration) into a list of just one element in order to disambiguate the “list of list” situation in the iteration. 
It is possible to use “capsul > pipeline > custom_nodes > reduce_node > ReduceNode” or the “mia_processes > bricks > tools > Files_To_List” brick. 

When the iteration is done [via input filter brick/process](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) it seems that the `ReduceNode` brick is used. 

When I iterate either [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)  using `ReduceNode`  brick  or [via input filter brick/process](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) I have an issue with the `ReduceNode` brick. 

If I iterate [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)  using `Files_To_List`  brick it is working. 

**Generated error**
```
Traceback:
  File "/home/gourieuxe/apps/sources_populse/populse_mia/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1544, in initialize
    self.test_init = self.init_pipeline()
  File "/home/gourieuxe/apps/sources_populse/populse_mia/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1649, in init_pipeline
    missing_mandat_param = self.get_missing_mandatory_parameters()
  File "/home/gourieuxe/apps/sources_populse/populse_mia/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1484, in get_missing_mandatory_parameters
    if node.context_name.split(".")[0] == "Pipeline":
AttributeError: 'ReduceNode' object has no attribute 'context_name'
```
(error in `get_missing_mandatory_parameters` [function](https://github.com/populse/populse_mia/blob/master/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L1485))

**To Reproduce**
Steps to reproduce the behavior [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table):
1. Open a project with at least 2 subjects / 2 documents in order to do an iteration 
2. In pipeline manager tab, add the smooth brick (mia_processes/bricks/preprocess/spm), export `in_files` parameter using `ReduceNode` brick , export output parameters:
![image](https://github.com/populse/populse_mia/assets/47973414/b3a48210-8a0c-45b1-95cd-665f98a19f20)
3. Check on the iterate pipeline button and click on "OK" (without checking in_files). It will create the pipeline to iterate
![image](https://github.com/populse/populse_mia/assets/47973414/989869c8-39c7-4cf4-9191-0c90ee5028e0)
4. Select inputs node and add the `in_file`, run the pipeline . The error is in the standard output.

**Comment by servoz** [comment] 2023-07-07 13:05
Thank's @manuegrx for this very clear ticket and with the `To reproduce` step that will help for the investigation.

It is not impossible that the problem comes from the mia side (change we made, because this `capsul > pipeline > custom_nodes > reduce_node > ReduceNode`cworked before, if I remember correctly) and not from the brick side.

I'm on another case and will look into it ASAP.

**Comment by denisri** [comment] 2023-07-07 14:32
`context_name` is an attribute set in pipeline nodes to provide them with their full name inside the pipeline (`pipeline.subpipeline.node_name` for instance). It is not totally mandatory in nodes (the attribute does not exist upon construction) but is normally set by Pipeline methods `add_process_node()`, `add_switch()` etc. But it had apparently been forbidden in `add_custom_node()`, and `ReduceNode` is a custom node, which explains the error.
I have added it. However other code in Capsul does not consider it as mandatory, each access to it is done via something like `getattr(node, 'context_name', node.name)`, not directly `node.context_name`.
Well, can you pull the modif in capsul and try again ?

**Comment by manuegrx** [comment] 2023-07-07 15:30
Thanks @denisri !
However it seems that I have still the same issue after updating Capsul with your last commit ! 

Maybe we need to change  node.context_name to getattr(node, 'context_name', node.name)  as proposed by @servoz

**Comment by servoz** [comment] 2023-07-07 15:55
Let's try again with a fresh master populse_mia, please.
@denisri is right we must have a default value if `in_context` is not a process attribute.
I'm in doing the necessary everywhere in mia, but for this ticket I think it's set, no?

**Comment by denisri** [comment] 2023-07-07 16:05
Well right, in the GUI, nodes added in the `PipelineDeveloperView` were not added via the `add_custom_node()` method, and did not get a `context_name`. I've changed that. Now on MIA side I haven't checked how nodes are added in the pipeline, there may be missing things. Now using `getattr()` everywhere is a bit painful and not very elegant, I admit. Maybe we could set a default value or a property in `Node`, I'm not sure...

**Comment by manuegrx** [comment] 2023-07-10 07:17
It is working with the update done in populse_mia thanks ! 
@servoz  do you want to keep the ticket open until all the changes in mia are completed ?

**Comment by servoz** [comment] 2023-07-10 07:38
I'll make the changes today and close this ticket if it's ok for you.

**Comment by servoz** [comment] 2023-07-10 08:26
We use in Mia [PipelineEditor.add_named_process()](https://github.com/populse/populse_mia/blob/9d8f0dc9744cb8d647fa3c983d4b6976caee6924/populse_mia/user_interface/pipeline_manager/pipeline_editor.py#L495
) to add node/process in a pipeline. In there, we use the parent class method[ PipelineDeveloperView. add_named_process().](https://github.com/populse/capsul/blob/903a51d92f710b62e33aa1754de9cf69388d90bd/capsul/qt_gui/widgets/pipeline_developer_view.py#L4029)
I haven't checked exactly what happens next, but I think it's OK. Can you confirm this, @denisri ?
I'm finishing changing the context name retrieval everywhere. It's better this way.

**Comment by servoz** [comment] 2023-07-10 10:07
For regular processes, [the node name is foo_1, foo_2](https://github.com/populse/capsul/blob/3c1fb750c20fa9aff96aa23d85271db2b7b6560b/capsul/qt_gui/widgets/pipeline_developer_view.py#L4038), etc. For custom nodes, [it's foo1, foo2](https://github.com/populse/capsul/blob/3c1fb750c20fa9aff96aa23d85271db2b7b6560b/capsul/qt_gui/widgets/pipeline_developer_view.py#L4131), etc.

In mia and mia_processes, we've adopted the foo_1 rule, I think because we're dealing with regular processes (which is why I mistakenly call them regular!).

I think it would be better to have a consistent name for all nodes? Would it be possible to change this for custom nodes (foo_n) in capsul ?

**Comment by servoz** [comment] 2023-07-10 10:21
context_name fixed everywhere in populse_mia.

**Comment by denisri** [comment] 2023-07-10 12:34
> For regular processes, [the node name is foo_1, foo_2](https://github.com/populse/capsul/blob/3c1fb750c20fa9aff96aa23d85271db2b7b6560b/capsul/qt_gui/widgets/pipeline_developer_view.py#L4038), etc. For custom nodes, [it's foo1, foo2](https://github.com/populse/capsul/blob/3c1fb750c20fa9aff96aa23d85271db2b7b6560b/capsul/qt_gui/widgets/pipeline_developer_view.py#L4131), etc.
> 
> In mia and mia_processes, we've adopted the foo_1 rule, I think because we're dealing with regular processes (which is why I mistakenly call them regular!).
> 
> I think it would be better to have a consistent name for all nodes? Would it be possible to change this for custom nodes (foo_n) in capsul ?

OK, it's done.

**Closed** 2023-07-10 12:52 UTC
