### ISSUE TITLE
Running a pipeline without specifying inputs or initialization crashes MIA, linked with #34

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#110] opened 2019-08-21 11:43 UTC
**Describe the bug**
If a user erroneously runs a pipeline without specifying an input file (version A of the bug) **or** without initializing the pipeline (version B of the bug), MIA crashes.

**Generated error (Version A)**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1581, in run
    study_config.run(pipeline, verbose=1)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 313, in run
    missing = process_or_pipeline.get_missing_mandatory_parameters()
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/process/process.py", line 914, in get_missing_mandatory_parameters
    if not check_trait(trait, value):
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/process/process.py", line 899, in check_trait
    for i, item in enumerate(value):
TypeError: '_Undefined' object is not iterable
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

QObject::~QObject: Timers cannot be stopped from another thread
```

**Generated error (Version B)**
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1581, in run
    study_config.run(pipeline, verbose=1)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 414, in run
    verbose)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 471, in _run
    **kwargs)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/run.py", line 102, in run_process
    returncode = process_instance._run_process()
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/process/process.py", line 1227, in _run_process
    raise ValueError('output_directory is not set but is mandatory '
ValueError: output_directory is not set but is mandatory to run a NipypeProcess
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

QObject::~QObject: Timers cannot be stopped from another thread
```

**To Reproduce**
1. Open MIA. In the pipeline manager, drag and drop the SPM Smooth brick in the _New Pipeline_ window. Export the _in_files_ and __smoothed_files_ plugs. 

**Version A of the bug**
2. Do **not** specify an input file.
3. Optionally Initialize the pipeline (nothing happens)
4. Click on "Run pipeline".

**Version B of the bug**
2. Specify an input file. Do **not** initialize the pipeline
3. Click on "Run pipeline".

**Expected behavior**
1. If a user runs a pipeline that has not yet been initialized, the initialization should be run automatically.
2. If a pipeline is initialized but input parameters are missing, the user should receive a warning and MIA should leave the pipeline uninitialized.
3. MIA should never crash.

**Desktop**
 - OS: Ubuntu 18.04
 - Populse_MIA version: 1.1.1
 - nipype version: 1.2.0
 - mia_processes version: 1.2.1

**Comment by servoz** [comment] 2019-08-21 13:36
I totally agree, MIA should never crash. This is no Windows ...
High priority in the "Prioritisation of issues to be resolved" Milestone

**Comment by M40V** [comment] 2019-08-28 15:07
We can forbid the user to run a pipeline if an initialization was not completed successfully before.
Also, if the iterate pipeline checkbox is checked, we should not be able to click on initialize pipeline.

**Comment by servoz** [comment] 2019-09-09 14:33
@M40V , I share your view. If we forbid the user to run a pipeline if the initialisation was not completed successfully, we fix at the same time the A and B points ! 

Moreover we can consider that the initialisation is always necessary before launching a run because we thought this step as a preparation and a check (currently this part is not yet very developed but it could be nice to work on the check part as soon as possible!) that nothing is wrong before the final run.

Thanks to the initialisation step, mia should never crash during the run stage.

There is still the problem of initialisation during a pipeline iteration. Currently the initialisation is integrated to the run stage (if nothing was changed recently). As we already discussed, I think that the initialisation should be a separate and a mandatory stage before a run stage, even for the iterative pipeline. Indeed, if the initialisation is included in the run, there is a risk of mia crash, or at best, if the exception is well catched, a pipeline stop after several hours without the user being immediately aware (and therefore a waste of time in the case of long calculations).

I think that getting the initialisation out of the run for a pipeline iteration can be a pretty substantial work. Perhaps we should open another issue for this special subject?

**Comment by M40V** [comment] 2020-01-16 16:39
It is currently possible to initialize and run a disabled pipeline, MIA doesn't crash but it might be better to keep the run action disabled if the pipeline is missing mandatory links.

**Comment by M40V** [comment] 2020-01-30 09:53
Since https://github.com/populse/populse_mia/commit/be2d616b10bbcd3176fa73e45be23f1419527580, the run action is disabled if the pipeline has disabled nodes. We should discuss if we want to keep this change before closing this issue.

**Comment by servoz** [comment] 2020-02-03 16:06
[not really fixed ...](https://github.com/populse/populse_mia/issues/142)

**Comment by servoz** [comment] 2020-02-28 10:54
I think that problem is now solved. The **expected behaviour** described in the first post is not the new current behaviour (now initialisation is mandatory before a run), but I think the main problem raised in this ticket is now addressed. I close this ticket and I will open a new one, for the initialisation in the case of an iteration (is it desirable? and can we make initialisation mandatory before a run?, even in the case of an iteration).

**Closed by servoz** 2020-02-28 10:54 UTC
Labels: bug
