### ISSUE TITLE
[Data Viewer] viewers modularity, genericity, startup etc

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#201] opened 2021-06-23 11:03 UTC
I have a few comments about the current status of viewers, it's related to #197 but I open another ticket to avoid "polluting" #197 which is a kind of roadmap, maybe not a discussion/issue report.
* `data_viewer_tab` imports anatomist unconditionally, which is probably not needed, and has an overhead (anatomist has itself many dependencies and takes some time and memory resources to import - as discussed in #200.
* the "genericity" and modularity of the viewers tab seems to be gone: viewer modules are hard-coded in the data_viewer_tab.py code, specific variables are used for specific viewers and thus cannot be changed or the list of viewers cannot be extended anymore. Maybe we could change this back to have an "open" list of viewers that could be extended (by plugins for instance) ?
* All viewers are instantiated at startup. This brings 2 major overheads:
  * it takes time (and memory) at startup because the Anatomist instance initializes lots of things, looks for plugins, etc etc. this time overhead could also be even increased if we implement other viewers for different kinds of data (such as graph plotting viewers, text or PDF viewers etc) if all are loaded and initialized.
  * all viewers are started and consume resources when only one is actually used at a given time, and probably a regular user will only use one during the whole session. It's also possible that a user doesn't use any viewer at all if he just wants to build and run a pipeline. Thus delaying viewers initialization when we need them in a lazy way would be better
* The anatomist viewer was only here to demonstrate how to integrate anatomist as a viewer in Populse_mia. Now that the Mia_viewer implements (or will implement) the same features in a better way (more user-friendly) and additional features, the former anatomist viewer shouid probably disappear.
* Extending the same idea: Mia_viewer is more or less a re-writing of ana_simple_viewer in what we hope will be a better and more convenient viewer. Should they both live (and be maintained), or should we not replace the former ana_simple_viewer with the new one ? The only thing about this is that parts specific to MIA (database access etc) should be kept separated because the ana_simple_viewer code should not depend on Mia.

**Comment by servoz** [comment] 2021-06-23 12:34
I share all your views.

We would like the Mia Data Viewer to be able to support several types of viewers and not only those based on anatomist.
We would like the user to be able to choose his viewer and to instantiate it only when needed and not at startup.

For your last point. I am not against totally outsourcing the ana_simple_viewer, as developed by @Celinnnne, in anatomist. This would simplify maintenance. 
As you know I am in favour of merging Populse and Brainvisa as much as possible and this goes in that direction. @Celinnnne is currently doing a very good job of implementing a user friendly version of ana_simple_viewer in mia's DataViewer and the problem is that her contract is very short (she's already done half of the time and only has 4 weeks left).
As you are very busy at the moment I think the most efficient is to continue to develop as we started and when we have a bit more time (beginning of september ?), we can think together about what we should improve and push on anatomist ?

**Comment by Celinnnne** [comment] 2021-06-25 14:41
Thanks for your comments and improvement ideas @denisri. We just pushed a new version on master which should respond as much as possible to your expectations. 

- anatomist is not imported unconditionally in data_viewer_tab.py anymore so Mia works also without viewers available
- some "genericity" is found again as the viewers are not hard coded anymore and a user can add his viewer below but maybe an easier way could be found (plugins as you suggested ...?)  
- Viewers are now initiated again when DataViewer tab is clicked

**Comment by denisri** [comment] 2021-06-25 14:49
That looks rather good ! Thanks...

**Comment by servoz** [comment] 2021-10-05 17:40
It seems the main points of this ticket have been addressed and that changes have been made in the requested direction.
It's time to close it!

**Closed by servoz** 2021-10-05 17:40 UTC
Labels: To discuss
