### ISSUE TITLE
Sometimes bricks in a pipeline are initialized twice

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#115] opened 2019-08-30 10:05 UTC
**Describe the bug**
The order in which bricks in a pipeline are initialized seems to be sub-optimal. Sometimes, a brick is initialized before all of the other bricks providing inputs are. Later, when the other bricks are ready, that brick is initialized again, with more inputs. This only happens, when the other inputs are optional. It looks as though optional inputs are not considered at all, when deciding on the initialization order of nodes.

I file this as a bug, not an enhancement, because the initialization may be time-consuming, when checks for SPM configuration are enabled.

**Generated error**
None

**To Reproduce**
1. Build a pipeline with at least three bricks, where a mandatory input of the last brick comes from an output of the first brick and an optional input of the last brick comes from an output of the second brick. 
2. Initialize the pipeline.
3. Initialization order may be: Brick1, Brick3, Brick2, Brick3

**Expected behavior**
When determining initialization order between two bricks, priority should be given to the one for which all inputs satisfied, with respect to one where connected optional inputs do not yet have values.

**Screenshots**
Example pipeline
![image](https://user-images.githubusercontent.com/11682353/64012606-53638800-cb1e-11e9-8a2e-0556dfeb1d6e.png)

Here, initialization order is:

1. aslrescaling1
2. aslrealign1
3. aslstats1
4. asloutlierdetection1
5. aslstats1

**Desktop**
 - OS: Ubuntu 18.04
 - Populse_MIA version: 1.1.1
 - nipype version: 1.2.0
 - mia_processes version: 1.2.1

**Comment by denisri** [comment] 2019-08-30 10:19
What kind of initialization is it (I don't have thinghs in mind right now...) ? Is it MIA-specific or is it in Capsul ?

**Comment by JanWP** [comment] 2019-08-30 14:29
I'm referring to the call of the _list_outputs_ method from [pipeline_manager_tab.py](python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py) (specifically, from [this line](https://github.com/populse/populse_mia/blob/a134c7af7007e2b6a76f89ec3030029d09da84cd/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L758) in the [init_pipeline](https://github.com/populse/populse_mia/blob/a134c7af7007e2b6a76f89ec3030029d09da84cd/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L541) method). So this seems to be MIA-specific.

**Comment by servoz** [comment] 2019-09-09 15:52
I think that this issue as to be fixed ASAP.
Medium-High priority in the "Prioritisation of issues to be resolved" Milestone.

**Comment by servoz** [comment] 2020-02-25 23:59
Sorry for the delay !!!
I'm not sure this problem comes from [this line](https://github.com/populse/populse_mia/blob/a134c7af7007e2b6a76f89ec3030029d09da84cd/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L758) and in fact I'm not sure it's really a problem ...

Since you give an example with bricks that are not in nipype or mia_processes, it's a bit difficult to reproduce and study exactly the problem ! Please can you give one example with bricks from nipype or mia_processes ?

In a nutshell: The priority is determined according to a ratio between the number of mandatory input plugs connected to the input node and the mandatory input plugs connected to one other brick. Then, when the priority tends towards zero, the initialisations take place in alphabetical order, and if an initialisation fails, it is retried later because the brick preceding it, at the time of its initialisation, will provoke again the initialisation of the brick which failed previously.
As an example:
- Launch Mia
- Import or open a project with for ex. one anat.nii and func.nii
- Go to Pipeline Manager
- In the New Pipeline tab, drag and drop the Spatial_preprocessing_1 brick from the mia_processes library
- On this Spatial_preprocessing_1 brick, right click and choose Edit sub-pipeline
- Click on the inputs node then click on the Filter buttons for the anat_file and func_files parameters in the controller then select the anat.nii and func.nii scan from the database, respectively, (right part of the window).
- Pipeline > Initialize pipeline

We observe initilisation of:
- realign1(high priority)
- list_duplicate1 (high priority)
- newsegment1
- normalize12_1
- normalize12_2 (falls)
- coregister1
- normalize12_2 (works)
- smooth1

The code for this is mainly before 
`\# Adding the brick to the bricks history `

and just after 
`\# If the output is connected to another node,`
`\# the latter is added to nodes_to_check`

in the init_pipeline() method of the populse_mia.user_interface.pipeline_manager.pipeline_manager_tab module.

These code parts can perhaps be improved, but it is not easy to automatically find the right order in one go!

**Comment by servoz** [comment] 2020-12-09 15:35
Fixed in release 2

**Closed by servoz** 2020-12-09 15:35 UTC
Labels: enhancement
